packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@t3-oss/env-nextjs': ^0.11.0
  '@tanstack/react-query': ^5.51.24
  '@trpc/client': 11.0.0-rc.482
  '@trpc/react-query': 11.0.0-rc.482
  '@trpc/server': 11.0.0-rc.482
  '@types/node': ^20
  next: 14.2.6
  next-auth: 5.0.0-beta.20
  superjson: 2.2.1
  zod: ^3.23.8
  prettier: ^3.3.3
  eslint: ^9.7.0
  typescript: ^5.5.3
  tsc-files: ^1.1.4
  'react-native': ~0.74.3
  zustand: 5.0.0-rc.0

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    '@types/react': ^18.3.3
    '@types/react-dom': ^18.3.0
