packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@hookform/resolvers': ^3.9.0
  '@tanstack/react-query': ^5.51.24
  '@t3-oss/env-nextjs': ^0.11.0
  '@trpc/client': 11.0.0-rc.482
  '@trpc/react-query': 11.0.0-rc.482
  '@trpc/server': 11.0.0-rc.482
  '@types/bcryptjs': ^2.4.6
  '@types/node': ^20
  bcryptjs: ^2.4.3
  clsx: ^2.1.1
  date-fns: ^3.6.0
  eslint: ^9.7.0
  expo-secure-store: ^13.0.2
  next: 14.2.6
  next-auth: 5.0.0-beta.22
  prettier: ^3.3.3
  react-hook-form: ^7.53.0
  react-native: ~0.74.3
  superjson: 2.2.1
  tailwind-merge: ^2.4.0
  tailwindcss: ^3.4.4
  tsc-files: ^1.1.4
  typescript: ^5.5.3
  use-debounce: ^10.0.3
  zod: ^3.23.8
  zustand: 5.0.0-rc.2

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    '@types/react': ^18.3.3
    '@types/react-dom': ^18.3.0
