name: iOS App Release Build

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*.ios'

env:
  EXPO_PUBLIC_API_URL: ${{ secrets.EXPO_PUBLIC_API_URL }}
  EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID: ${{ secrets.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID }}

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/') && endsWith(github.ref, '.ios')
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: 'pnpm'

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build iOS app
        run: |
          cd ./apps/mobile
          eas build --local --platform=ios --output=${{ github.workspace }}/app.ipa --non-interactive --no-wait

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/app.ipa
          name: Release ${{ github.ref_name }}
